### ISSUE TITLE
[Epic] Improve dashboard

### ISSUE THREAD

**Issue by HaiseB** [HaiseB/P5_blogPhp#12]
### 1 - Challenges

Dashboard is currently "not that great", we can improve it for a better interface 

datatable -> https://datatables.net/

confrim delete -> https://stackoverflow.com/questions/16962280/delete-button-and-confirmation

### 2 - Vision

easier dashboard to work with

### 3 - Focus Areas

simple and "strong"

### 4 - Mission

improve the current view with a

### 5 - Activity/Deliverables

- [ ]  Improve view of the dashboard
- [x]  add post delete button
- [ ] confirm before delete pop up

### 6 - Measure

NFN
